
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  AztecAddress,
  AztecAddressLike,
  CompleteAddress,
  Contract,
  ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  ContractMethod,
  DeployMethod,
  EthAddress,
  EthAddressLike,
  FieldLike,
  Fr,
  Point,
  PublicKey,
  Wallet,
} from '@aztec/aztec.js';
import CoinTossContractArtifactJson from './CoinToss.json' assert { type: 'json' };
export const CoinTossContractArtifact = CoinTossContractArtifactJson as ContractArtifact;

/**
 * Type-safe interface for contract CoinToss;
 */
export class CoinTossContract extends ContractBase {
  
  private constructor(
    completeAddress: CompleteAddress,
    wallet: Wallet,
    portalContract = EthAddress.ZERO
  ) {
    super(completeAddress, CoinTossContractArtifact, wallet, portalContract);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, CoinTossContract.artifact, wallet) as Promise<CoinTossContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, divinity: AztecAddressLike, private_oracle: AztecAddressLike, house: AztecAddressLike, token: AztecAddressLike, bet_amount: FieldLike) {
    return new DeployMethod<CoinTossContract>(Point.ZERO, wallet, CoinTossContractArtifact, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public key to derive the address.
   */
  public static deployWithPublicKey(publicKey: PublicKey, wallet: Wallet, divinity: AztecAddressLike, private_oracle: AztecAddressLike, house: AztecAddressLike, token: AztecAddressLike, bet_amount: FieldLike) {
    return new DeployMethod<CoinTossContract>(publicKey, wallet, CoinTossContractArtifact, Array.from(arguments).slice(2));
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return CoinTossContractArtifact;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public methods!: {
    
    /** _emit_bet_escrow(escrow_randomness: field) */
    _emit_bet_escrow: ((escrow_randomness: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** compute_note_hash_and_nullifier(contract_address: field, nonce: field, storage_slot: field, preimage: array) */
    compute_note_hash_and_nullifier: ((contract_address: FieldLike, nonce: FieldLike, storage_slot: FieldLike, preimage: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_bet(bet: boolean, user_transfer_nonce: field, house_escrow: field, house_settle_escrow_nonce: field) */
    create_bet: ((bet: boolean, user_transfer_nonce: FieldLike, house_escrow: FieldLike, house_settle_escrow_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_config_unconstrained() */
    get_config_unconstrained: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_results_unconstrained(owner: struct, start_offset: integer) */
    get_results_unconstrained: ((owner: AztecAddressLike, start_offset: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_user_bets_unconstrained(user: struct, start_offset: integer) */
    get_user_bets_unconstrained: ((user: AztecAddressLike, start_offset: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** oracle_callback(answer: field, data: array) */
    oracle_callback: ((answer: FieldLike, data: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** settle_bet(bet_id: field) */
    settle_bet: ((bet_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };
}
